version: '3'
services:
  srm_nginx_173_100:
    build:
      context: ./services/nginx
    container_name: srm_nginx_173_100
    ports:
      - "81:80"
    volumes:
      - ./services/nginx/conf.d:/conf/conf.d/:rw
      - ./services/nginx/nginx.conf:/conf/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx/:rw
    networks:
      nginx:
        ipv4_address: '173.200.7.100'
networks:
  nginx:
    ipam:
      config:
        - subnet: 173.220.7.0/24
