version: '3.6'
services:
  srm_rabbitmq_174_2:
    image: rabbitmq:3.7-management
    networks:
      rabbitmq:
        ipv4_address: '174.220.7.2'
    container_name: 'srm_rabbitmq_174_2'
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: mq2
    environment:
      - RABBITMQ_ERLANG_COOKIE='rabbitcookie'
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - "./2:/mq"
  srm_rabbitmq_174_3:
    image: rabbitmq:3.7-management
    networks:
      rabbitmq:
        ipv4_address: '174.220.7.3'
    container_name: 'srm_rabbitmq_174_3'
    ports:
      - "15673:15672"
      - "5673:5672"
    hostname: mq3
    environment:
      - RABBITMQ_ERLANG_COOKIE='rabbitcookie'
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - "./3:/mq"
  srm_rabbitmq_174_4:
    image: rabbitmq:3.7-management
    networks:
      rabbitmq:
        ipv4_address: '174.220.7.4'
    container_name: 'srm_rabbitmq_174_4'
    ports:
      - "15674:15672"
      - "5674:5672"
    hostname: mq4
    environment:
      - RABBITMQ_ERLANG_COOKIE='rabbitcookie'
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - "./4:/mq"
networks:
  rabbitmq:
    driver: bridge
    ipam:
      config:
        - subnet: 174.220.7.0/24
